[config]
schemaVersion = "0.0.1"

[package]
namespace = "Ardot66"
name = "Enemy_Overhaul"
versionNumber = "1.0.11"
description = "(Reaper now overhauled!) Overhauls or improves the AI of the Trudge, Robe, Reaper, Headman, Huntsman, Gnome... and even pits? See description for more information!"
websiteUrl = "https://github.com/Ardot66/REPO.EnemyOverhaul"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Build"

[[build.copy]]
source = "./bin/Debug/netstandard2.1/EnemyOverhaul.dll"
target = "./"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./"

[general]
repository = "https://thunderstore.io"

[publish]
communities = ["repo"]

[publish.categories]
"repo" = [ "mods", "monsters", "serverside"]


