[config]
schemaVersion = "0.0.1"

[package]
namespace = "Ardot66"
name = "Enemy_Overhaul"
versionNumber = "1.0.7"
description = "Overhauls or improves the AI of the Trudge, Robe, Headman, Huntsman, Gnome... and even pits? See description for more information!"
websiteUrl = "https://github.com/Ardot66/REPO.EnemyOverhaul"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Build"

[[build.copy]]
source = "./bin/Debug/netstandard2.1/EnemyOverhaul.dll"
target = "./"

[general]
repository = "https://thunderstore.io"

[publish]
communities = ["R.E.P.O."]

[publish.categories]
"R.E.P.O." = [ "mods", "monsters", "server-side"]


